modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPLv3"
issueTrackerURL="https://github.com/TyrellPlayz/ZLib/issues" #optional
[[mods]]
modId="zlib"
version="${mod_version}"
displayName="ZLib"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="zlib.png" #optional
authors="TyrellPlayz" #optional
description='''
A libary mod for mods created by me.
'''
[[dependencies.zlib]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.zlib]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
